#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# The pre-commit hook runs pretty-check & lint-check, so just build and test here.
# A full check is done in the GitHub build-test action anyway.
npm run --silent build
npm test
